services:
  # * phpmyadmin *
  phpmyadmin:
    container_name: pma
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - 9090:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - ustarg

networks:
  ustarg:
    driver: bridge
