services:
  # * phpmyadmin *
  phpmyadmin:
    container_name: pma
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 9090:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3307
    networks:
      - ustarg

networks:
  ustarg:
    driver: bridge
