services:
  # * PHP8.4 *
  php:
    container_name: php8_4
    restart: unless-stopped
    build:
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./backend:/app
    working_dir: /app
    user: '1000:1000'
    ports:
      - 9000:9000
    command: php -S 0.0.0.0:9000 -t /app
    networks:
      - ustarg

  # * MySQL9 *
  mysql:
    container_name: mysql
    image: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - ustarg

networks:
  ustarg:
    driver: bridge
